version: 2.1

#Warns Circleci that setup is going to happen
setup: true

orbs:
  continuation: circleci/continuation@0.1.2

executors:
  base:
    docker:
      - image: cimg/base:2021.04
    working_directory: /tmp/stdcheck.com

commands:
  git_check_no_promote:
    description: Checks if the commit contains the "No promote" tag, and writes the result to the file ./is-no-promote.
    steps:
      - run:
          name: Check "No Promote" Tag
          command: .circleci/bin/git/check-no-promote.sh

jobs:
  check-no-promote:
    executor: base
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      -  git_check_no_promote

workflows:
  version: 2
  setup:
    jobs:
      - check-no-promote
