version: 2.1

commands:
  git_submodule_init:
    steps:
      - run:
          name: placefolder for holding submodules
          command: echo "submodules initialized successfully"

  freeze_if_nopromote:
    steps:
      - run:
          name:  If its tagged No Promote we Freeze this.
          command: .circleci/bin/check_and_freeze.sh

  get_pr_title:
    steps:
      - run:
          command: |

            PR_NUMBER=$(echo "$CIRCLE_PULL_REQUEST" | sed "s/.*\/pull\///")
            echo "PR_NUMBER: $PR_NUMBER"
            echo "CircleCI PR Number: $CIRCLE_PR_NUMBER"	
            echo "export GITHUB_PR_NUMBER=$PR_NUMBER" >> $BASH_ENV
            
            API_GITHUB="https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
            PR_REQUEST_URL="$API_GITHUB/pulls/$PR_NUMBER"
            
            PR_RESPONSE=$(curl -H "Authorization: token $GITHUB_TOKEN" "$PR_REQUEST_URL")
            PR_TITLE=$(echo $PR_RESPONSE | jq -e '.title' | tr -d '"')

            echo "PR_TITLE: $PR_TITLE"

            echo "export GITHUB_PR_TITLE='${PR_TITLE/"'"/}'" >> $BASH_ENV

jobs:
  freeze-no-promote:
    docker:
      - image: cimg/php:8.0.13
    steps:
      - checkout
      - run:
          name: Rebase to main
          command: |
            git fetch origin
            git merge origin/main --no-edit
      - git_submodule_init
      - get_pr_title
      - freeze_if_nopromote

  test-bash:
    parallelism: 1
    docker:
      - image: cimg/php:8.0.13
    steps:
      - run:
          name: Run bash tests
          command: echo "Bash Working OK"

  build:
    parallelism: 1
    docker:
      - image: cimg/php:8.0.13
    steps:
      - run:
          name: Build the app
          command: echo "app built! OK"

  static_analysis:
    docker:
      - image: cimg/php:8.0.13
    steps:
      - run:
          name: Run static analysis tests
          command: echo " Static Analized"

  standarts_enforcing:
    docker:
      - image: cimg/php:8.0.13
    steps:
      - run:
          name: Run the standart enforcing tests
          command: echo "standarts enforced"

  test-integration:
    docker:
      - image: cimg/php:8.0.13
    steps:
      - run:
          name: Run the integration tests
          command: echo "Integration tested"

  deploy:
    docker:
      - image: cimg/php:8.0.13
    steps:
      - run:
          name: Deploys the App in the site
          command: echo "App Deployed Oh Damn"

  other-deploy:
    docker:
      - image: cimg/php:8.0.13
    steps:
      - run:
          name: Deploys something else
          command: echo "Deployed something that does not break the app"

  check-no-promote:
    docker:
      - image: cimg/php:8.0.13
    steps:
      - run:
          name: Checks if the PR has the No Prmote tag
          command: echo "Are you promoted?"

  promote:
    docker:
      - image: cimg/php:8.0.13
    steps:
      - run:
          name: Promotes the app to the main site
          command: echo "Promoted!"

  revert:
    docker:
      - image: cimg/php:8.0.13
    steps:
      - run:
          name: Reverts the current commit
          command: echo "Promoted!"

  unfreeze:
    docker:
      - image: cimg/php:8.0.13
    steps:
      - run:
          name: Unfreezes the Merge
          command: echo "Unfreezing Merge!"


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - freeze-no-promote
      - test-bash:
          requires:
            - freeze-no-promote
      - build:
          requires:
            - test-bash
      - static_analysis:
          requires:
            - build
      - standarts_enforcing:
          requires:
            - build
      - test-integration:
          requires:
            - static_analysis
            - standarts_enforcing
      - deploy:
          requires:
            - build
      - other-deploy:
          requires:
            - build
      - check-no-promote:
          requires:
            - deploy

      - promote-hold:
          type: approval
          requires:
            - check-no-promote

      - revert-hold:
          type: approval
          requires:
            - check-no-promote

      - promote:
          requires:
            - promote-hold
      - revert:
          requires:
            - revert-hold
      - unfreeze:
          requires:
            - promote
      - unfreeze:
          requires:
            - revert