version: 2.1

commands:
  git_submodule_init:
    steps:
      - run:
          name: placefolder for holding submodules
          command: echo "submodules initialized successfully"

  unfreeze:
    steps:
      - run:
          name : Unfreezes
          command: echo "Unfreezing Merge"

  freeze_if_nopromote:
    steps:
      - run:
          name:  If its tagged No Promote we Freeze this.
          command: .circleci/bin/check_and_freeze.sh

  get_pr_promote:
    steps:
      - run:
          command: .circleci/bin/get_pr_promote.sh

  git_configure:
    steps:
      - run:
          name: Configure Git
          command: .circleci/bin/configure.sh


  promote:
    steps:
      - run:
          command: ~/project/.circleci/bin/promote.sh

  revert:
    steps:
      - run:
          command: ~/project/.circleci/bin/revert.sh

jobs:

  freeze-no-promote:
    docker:
      - image: cimg/php:8.0.13
    steps:
      - checkout
      - git_submodule_init
      - get_pr_promote
      - freeze_if_nopromote

      - persist_to_workspace:
          root: workspace
          paths:
            - is-no-promote

  test-bash:
    parallelism: 1
    docker:
      - image: cimg/php:8.0.13
    steps:
      - checkout
      - git_submodule_init
      - get_pr_promote
      - freeze_if_nopromote
      - run:
          name: Run bash tests
          command: echo "Bash Working OK"

  build:
    parallelism: 1
    docker:
      - image: cimg/php:8.0.13
    steps:
      - run:
          name: Build the app
          command: echo "12345" > version_name
      - run:
          name: Send a service
          command: echo "servo" > service
      - persist_to_workspace:
          root: .
          paths:
            - version_name
            - service

  static_analysis:
    docker:
      - image: cimg/php:8.0.13
    steps:
      - run:
          name: Run static analysis tests
          command: echo " Static Analized"

  standarts_enforcing:
    docker:
      - image: cimg/php:8.0.13
    steps:
      - run:
          name: Run the standart enforcing tests
          command: echo "standarts enforced"

  test-integration:
    docker:
      - image: cimg/php:8.0.13
    steps:
      - run:
          name: Run the integration tests
          command: echo "Integration tested"

  deploy:
    docker:
      - image: cimg/php:8.0.13
    steps:
      - run:
          name: Deploys the App in the site
          command: echo "App Deployed Oh Damn"

  other-deploy:
    docker:
      - image: cimg/php:8.0.13
    steps:
      - run:
          name: Deploys something else
          command: echo "Deployed something that does not break the app"

  check-no-promote:
    docker:
      - image: cimg/php:8.0.13
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Checks if the PR has the No Prmote tag
          command: |
            noPromote=$(cat /tmp/workspace/is-no-promote)
            if [ "$noPromote" == false ]; then
              echo "Commit does not have the No promote tag. Halting downstreamn jobs"
              .circleci/bin/halt.sh
            fi


  promote:

    docker:
      - image: cimg/php:8.0.13
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - promote
      - unfreeze

  revert:
    docker:
      - image: cimg/php:8.0.13
    steps:
      - checkout
      - git_configure
      - add_ssh_keys:
          fingerprint:
            - b7:9d:17:5e:57:10:1b:ab:ad:d4:97:8d:1b:03:0a:ac
      - revert
      - unfreeze

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - freeze-no-promote:
          filters:
            branches:
              only:
                - main
      - test-bash
      - build:
          requires:
            - test-bash
      - static_analysis:
          requires:
            - build
      - standarts_enforcing:
          requires:
            - build
      - test-integration:
          requires:
            - static_analysis
            - standarts_enforcing
      - deploy:
          requires:
            - build
      - other-deploy:
          requires:
            - build
      - check-no-promote:
          requires:
            - deploy
            - freeze-no-promote
          filters:
            branches:
              only:
                - main

      - promote-hold:
          type: approval
          requires:
            - check-no-promote
          filters:
            branches:
              only:
                - main

      - revert-hold:
          type: approval
          requires:
            - check-no-promote
          filters:
            branches:
              only:
                - main

      - promote:
          requires:
            - promote-hold
          filters:
            branches:
              only:
                - main
      - revert:
          requires:
            - revert-hold
          filters:
            branches:
              only:
                - main
