version: 2.1

#Warns Circleci that setup is going to happen
setup: true

orbs:
  continuation: circleci/continuation@0.1.2

executors:
  base:
    docker:
      - image: cimg/base:2021.04
    working_directory: /tmp/stdcheck.com

commands:
  git_check_no_promote:
    description: Checks if the commit contains the "No promote" tag, and writes the result to the file ./is-no-promote.
    steps:
      - run:
          name: Check "No Promote" Tag
          command: .circleci/bin/git/check-no-promote.sh

  greeting:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run: echo "Hello <<parameters.to>>"


jobs:

  select-workflow:
    executor: base
    steps:
      - checkout
      - git_check_no_promote
      - run:
          name: Saves the No promote value to an Bash Env Variable
          command: |
            cat is-no-promote
            echo "export NO_PROMOTE=$(cat is-no-promote)" >> $BASH_ENV
      - run:
          name: Creates parameters in a json file to pass to the next orb
          command: |
            echo '{ "is-no-promote": "'$NO_PROMOTE'" }' >> test.json
      - continuation/continue:
          configuration_path: .circleci/continue.yml
          parameters: test.json



workflows:
  version: 2
  setup:
    jobs:
      - select-workflow
