version: 2.1

#Warns Circleci that setup is going to happen
setup: true

orbs:
  continuation: circleci/continuation@0.1.2

executors:
  base:
    docker:
      - image: cimg/base:2021.04
    working_directory: /tmp/stdcheck.com

commands:

  get_pr_promote:
    steps:
      - run:
          command: .circleci/bin/get_pr_promote.sh
jobs:

  check-no-promote:
    executor: base
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Checks if the PR has the No Prmote tag
          command: |
            noPromote=$(cat /tmp/workspace/is-no-promote)
            if [ "$noPromote" == false ]; then
              echo "Commit does not have the No promote tag. Halting downstreamn jobs"
              .circleci/bin/halth.sh
            fi

workflows:
  version: 2

  setup:
    executor: continuation/default
    steps:
      - checkout;
      - check-no-promote;
        
