version: 2.1

parameters:
  is-no-promote:
    type: string
    default : "false"

executors:
  base:
    docker:
      - image: cimg/base:2021.04
    working_directory: /tmp/stdcheck.com

workflows:
  version: 2

  no-promote-workflow:
    jobs:
      - promote

commands:
  greeting:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run: echo "Hello <<parameters.to>>"

jobs:

  promote:
    executor: base
    steps:
      - checkout
      - greeting:
          to: <<pipeline.parameters.is-no-promote>>
      - run:
          name: Checks if the PR has the No promote tag.
          command: echo "Promote!"

  no-promote:
    executor: base
    steps:
      - checkout
      - run :
          name: Notice we are on No Promote
          command : echo "No Promote!"
