version: 2.1

parameters:
  is-no-promote:
    type: boolean
    default : false

executors:
  base:
    docker:
      - image: cimg/base:2021.04
    working_directory: /tmp/stdcheck.com

workflows:
  version: 2
  normal-workflow:
    jobs:
      - promote

  no-promote-workflow:
    when:
      and:
        - equal: << pipeline.parameters.is-no-promote >>
        - equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - no-promote

  promote-workflow:
    when:
      and:
        - not: << pipeline.parameters.is-no-promote >>
        - equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - promote

commands:
  greeting:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run: echo "Hello <<parameters.to>>"

jobs:

  promote:
    executor: base
    steps:
      - checkout
      - run:
          name: Notice we are on promote
          command: echo "Promote!"

  no-promote:
    executor: base
    steps:
      - checkout
      - run :
          name: Notice we are on No Promote
          command : echo "No Promote!"
