version: 2.1

parameters:
  is-no-promote:
    type: boolean
    default : false

executors:
  base:
    docker:
      - image: cimg/base:2021.04
    working_directory: /tmp/stdcheck.com

workflows:
  version: 2

  no-promote-workflow:
    when: << pipeline.parameters.is-no-promote >>
    jobs:
      - no-promote

  promote-workflow:
    when:
      - not: << pipeline.parameters.is-no-promote >>
    jobs:
      -promote


jobs:
  promote:
    executor: base
    steps:
      - checkout
      - run:
          name: Checks if the PR has the No promote tag.
          command: echo "Promote!"

  no-promote:
    executor: base
    steps:
      - checkout
      - run :
          name: Notice we are on No Promote
          command : echo "No Promote!"



