version: 2.1

parameters:
  promote:
    type: boolean
    default : true

executors:
  base:
    docker:
      - image: cimg/base:2021.04
    working_directory: /tmp/stdcheck.com

workflows:
  version: 2

  promote-workflow:
    when: << pipeline.parameters.promote >>
    jobs:
      - promote

  no-promote-workflow:
    when:
      not: << pipeline.parameters.promote >>
    jobs:
      - no-promote




jobs:
  promote:
    executor: base
    steps:
      - checkout
      - run :
        name: Notice we are on Promote
        command : echo "Promote!"

  no-promote:
    executor: base
    steps:
      - checkout
      - run :
        name: Notice we are on No Promote
        command : echo "No Promote!"



